spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000
      client:
        registration:
          cognito:
            client-id: 7ncoq4ft23f4nhg9tiikkdqm9t
            client-secret: 1cn31938ai0eaichoks5esdmmder6hv5gsebjdv4i90986gob3j5
            scope:
              - phone
              - openid
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_R96CXx8lC
            user-name-attribute: username
library:
  cognito:
    domain: https://us-east-R96CXx8lC.auth.us-east-1.amazoncognito.com
    logout-redirect: http://localhost:8080/
security:
  jwt:
    algorithm: HmacSHA256
    secret: super-secret
